name: Continuous Integration

on:
  push:
    branches: [ trunk ]

jobs:
  tests:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run the tests
      uses: cross-platform-actions/action@v0.13.0
      with:
        shell: sh
        operating_system: freebsd
        architecture: x86-64
        version: '13.2'
        run: |
          sudo sed -i '' -e 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf
          sudo pkg install -y git nimble libX11
          export PATH=$PATH:/home/runner/.nimble/bin:/usr/local/nim/bin
          nimble -y debug
          nimalyzer tools/nimalyzer.cfg
          nimble -y release
