name: Continuous Integration

on:
  push:
    branches: [ trunk ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run the tests
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          sed -i '' -e 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf
          pkg install -y git nimble ca_root_nss libX11
        run: |
          export PATH=$PATH:$HOME/.nimble/bin:/usr/local/nim/bin
          git config --global --add safe.directory /home/runner/work/winecellar/winecellar
          nimble -y debug
          nimalyzer tools/nimalyzer.cfg
          nimble -y release
